services:
  influxdb3-core:
    image: influxdb:3-core
    container_name: influxdb3
    ports:
      - "8181:8181"
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      #- --plugin-dir=/var/lib/influxdb3/plugins # Optional: only needed for processing engine plugins
      # for this project we use isda_streaming to transform data, so we don't need plugins
    volumes:
      - influxdb3-data:/var/lib/influxdb3/data
      #- influxdb3-plugins:/var/lib/influxdb3/plugins
    restart: unless-stopped

  explorer:
    image: influxdata/influxdb3-ui
    container_name: influxdb3-explorer
    pull_policy: always
    command: ["--mode=admin"]
    ports:
      - "8888:80"
    volumes:
      - ./db:/db:rw
      - ./config:/app-root/config:ro
    restart: unless-stopped

volumes:
  influxdb3-data:
  #influxdb3-plugins: